server-startup:
  big-fat-bloody-message-enabled: false

weapon:
  lore:
    - ' '
    - '&7Info'
    - '&7» Type: &f{weapon-type}'
    - '&7» Rarity: &f{weapon-rarity}'
    - '&7» Required level: &f{weapon-required-level}'
    - ' '
    - '&7Weapon Stats'
    - '&7» Damage: &f{weapon-min-damage}&7-&f{weapon-max-damage}'
    - '&7» Cooldown: &f{weapon-attack-cooldown}'
    - ' '
    - '&7Scroll Sockets'
    - '&7» &f{weapon-scroll-sockets}'
    - ' '
    - '&7Gem Sockets'
    - '&7» &f{weapon-gem-sockets}'
    - ' '
    - '&7Weapon Ability'
    - '&7» &f{weapon-ability-name}'
    - '&7» Cooldown: &f{weapon-ability-cooldown}'
    - '&7» Cost: &f{weapon-ability-mana}'
    - '&7» &f{weapon-ability-description}'
    - ' '
